### ISSUE TITLE
Replace FisherPrice vec3 class with VecGeom/Vector3D

### ISSUE THREAD

**Issue by shefmarkh** [apt-sim/AdePT#28]
Hello,

In the initial version of the Alpaka FisherPrice a vec3 class is included. This was developed mainly to learn more about how to write code for GPU. Myself,Davide and @drbenmorgan discussed that it could be replaced with:

https://gitlab.cern.ch/VecGeom/VecGeom/-/blob/master/VecGeom/base/Vector3D.h

Cheers,

Mark

**Comment by agheata** [comment]
Good choice since we need to fix the vector type used to communicate to physics/geometry. 
To be noted however that the layout of vecgeom::Vector3D depends on the backend chosen for VecGeom compilation (i.e. derivation for a Vc aligned type or not). If compiling VecGeom with Vc backend, the host/device layouts will not match, so host<->device value or pointer casting does not work properly. All OK if compiling VecGeom with BACKEND=cuda

**Comment by shefmarkh** [comment]
Is it a correct understanding that to run an algorithm, using Vector3D, on a GPU one must compile VecGeom with BACKEND=cuda, whilst for CPU one must instead compile with VC? 

Cheers,

Mark

**Comment by WitekPokorski** [comment]
Closing the issue as FisherPrice example is not supported anymore (and not relevant).
