### ISSUE TITLE
Adding a geometry example using VecGeom

### ISSUE THREAD

**Issue by agheata** [apt-sim/AdePT#38]
We need an example of usage of VecGeom navigation in CUDA kernels. As a first step, we can port the RaytracerBenchmark example from the raytracer_prot branch in VecGeom as example in AdePT, then modify it to use AdePT helpers/infrastructure. Few items along this path:
* The example is required to compile using VecGeom master branch. It will need to link with VecGeom::vecgeomcuda VecGeom::vecgeom and VecGeom::vgdml. The example runs the same code on both host/device - this functionality needs to be preserved
* We should try to use rays allocated using BlockData<T> containers and convert the kernel to run with copcore::Launcher in a first phase (then try using other launching schemas such as Alpaka, ...)
* Refactor the navigation methods as separate class LoopNavigator. Now this is implemented in source/benchmarking/Raytracer.cpp (header defined in VecGeom/VecGeom/benchmarking.Raytracer.h). The idea is that the LoopNavigator can be reused after (and possibly putting it in VecGeom), but at the beginning can stay in the ray-tracer example folder.
* Evolve the models in this ray-tracer to handle secondary rays (reflection/refraction) to exercise a dynamic population of tracks
* Use this as performance benchmark as evolving the framework/adding optimised navigators

**Comment by antoniopetre** [comment]
First, the RaytraceBenchmark example was exported and the compilation issues were resolved. Then, the navigation methods from ```Raytracer.cpp``` were exported in a separate class, called LoopNavigator.
Next, the rays were allocated from BlockData containers. Initially, CPU used ```Raytracer::PropagateRays``` function and GPU used ```renderKernel``` function for propagating all the rays. I refactored these methods in order to have a common function for both  backends and to run it with copcore::Laucher.
Next, I refactored the main part from ```RaytraceBenchmark.cpp``` in order to have the same calling sequence for CPU/GPU.
