### ISSUE TITLE
Test G4HepEM for use in physics processes in AdePT

### ISSUE THREAD

**Issue by drbenmorgan** [apt-sim/AdePT#57]
Presented at this week's SFT meeting by @mnovak42:

https://indico.cern.ch/event/983367/#1-g4hepem-rd-project

G4HepEM is an R&D project focussing on performant EM physics data and processes, including targeting accelerators. The project is on GitHub at https://github.com/mnovak42/g4hepem

As discussed in this morning's meeting, we should explore its use in AdePT for implementing physics data and processes so this issue is to start identifying tasks. A rough outline, with further comment/additions welcome include:

- How to integrate in AdePT's build? Git submodule? CMake `FetchContent`?
- Minimal example apps to demo init/run using the interfaces
- Connect up to ongoing AdePT code

No assignees as such yet, but pinging those involved in discussion: @WitekPokorski @amadio @agheata @jonapost 

Please add anyone else I've missed (or add yourself!)

**Comment by hahnjo** [comment]
From a design perspective, `G4HepEM` seems very nice for R&D: the clear separation of init and run time, the C-like `struct`s and no virtual inheritance. On the other hand, I see the two points that hinder "easy" integration:
1. The `G4HepEmRun` library has no CUDA yet and the functions are defined in source files. One option could be to move the implementation to header files that can be included, with the advantage that the compiler could inline function calls which tend to be expensive on the GPU.
2. While the different layout of `G4HepEmElectronDataOnDevice` could improve memory coalescing compared to `G4HepEmElectronData` (if consecutive warps indeed access consecutive parts of the data), I'm not sure how this can work for a common implementation. The current functionality in `G4HepEmRun` is tailored towards `G4HepEmElectronData` and passes the argument through the different levels. For example, `apps/tests/ElectronEnergyLoss/` seems to duplicate `GetRestRange` and `GetRestDEDX` in `TestElossDataRangeDEDXKernel` instead of calling them.

**Comment by mnovak42** [comment]
#### 1. 
 ``G4HepEmRun`` do not have the CUDA functions because there are dependencies e.g. on the final track representation (as I discussed during my presentation). Everything is  known in ``G4HepEm`` for the CPU version but not for the (possible more than one) GPU  implementation(s).  This is why CUDA implementations are not given as part of the ``G4HepEmRun``, contrary to the ``G4HepEmData`` library, where all the required informations are known (that are needed to transfer the data to the device).
 
However, when the required information is available (e.g. what is the track representation, how they accessed, how random numbers are generated, etc.)  then the provided CPU implementations can be easily transformed to the corresponding CUDA functions.  Some parts of these functions, e.g. run time interpolations of the global data structures, are implemented in CUDA:

 - they are not provided as part of the ``G4HepEmRun`` : their final form should be determined by the complete CUDA tracking/stepping environment 
 - they are provided in the ``/app/tests`` directory: for each data structure as part of their unit test using a given input-output representation (i.e. as an example)

#### 2.
2. As mentioned above, ``G4HepEmRun`` contains the CPU implementation of the simulation because this is the only environment to which all information is available in ``G4HepEm``. Therefore, the corresponding function implementations rely  on the host side data structures. However, if one consult the provided unit tests in ``app/tests`` and have a look to the provided CUDA side functions:

 - they are very similar to the corresponding host side functions 
 - the main difference that their data structure input argument is the device side data structure (and having more than one inputs/outputs)

Of course, these are enough to require different host and device side run time functions (even for these that are just performing the interpolations). Those in the unit tests are supposed to provide a base line for their CUDA side implementation in your project (that ``G4HepEm`` do not know anything about).  So I don't understand why it's surprising the duplication there (for testing the device side data structures). Or did I miss something here?  


#### The expected utilisation of ``G4HepEm`` in a GPU simulation project is something like:

   -   use ``G4HepEm`` directly to perform the physics data initialisations and to transform all data required at run-time to the device (these do not require anything form the ``G4HepEmRun`` library and can be done easily) 
   -  use the functions, implemented in the ``G4HepEmRun`` library (especially those from ``G4HepEmElectronManager `` and later ``G4HepEmGammaManager`` ) as guide lines regarding how to perform a physics simulation step
   - the required functions can be transformed to the corresponding CUDA functions easily, some of them are even provided as examples as part of the unit test (with a given input/output pattern)
  - transform those run-time functions according to your environment and tracking to device side functions in your project

**Comment by drbenmorgan** [comment]
Think we can close this as G4HepEm is now submodule-d for use/investigation in AdePT. Other issues/uses can go in separate issues.
